# Generated by Django 5.2.8 on 2025-11-15 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("phone_number", models.IntegerField()),
                ("state", models.CharField(blank=True, max_length=67, null=True)),
                ("city", models.CharField(blank=True, max_length=67, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("date_created", models.DateTimeField(auto_now=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
