# Generated by Django 5.2.8 on 2025-11-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
