"""
Django settings for Ecomerce_app project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from util import verify_env
import os
import dj_database_url
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-fnmui1v$v)qx69*u8m)o-69bf$46_kg!(9heu!knm$#84rflp$"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
  "alx-project-nexus-ecommerce-backend.onrender.com",
  "localhost",
  "127.0.0.1",
]



# Application definition

INSTALLED_APPS = [
  "django.contrib.admin",
  "django.contrib.auth",
  "django.contrib.contenttypes",
  "django.contrib.sessions",
  "django.contrib.messages",
  "django.contrib.staticfiles",
  "rest_framework",
  "users.apps.UsersConfig",
  "product_listing",
  "product_payment",
  "security",
  "drf_yasg",
  #"rest_framework_simplejwt.tokens_blacklist"
]

MIDDLEWARE = [
  "django.middleware.security.SecurityMiddleware",
  "django.contrib.sessions.middleware.SessionMiddleware",
  "django.middleware.common.CommonMiddleware",
  "django.middleware.csrf.CsrfViewMiddleware",
  "django.contrib.auth.middleware.AuthenticationMiddleware",
  "django.contrib.messages.middleware.MessageMiddleware",
  "django.middleware.clickjacking.XFrameOptionsMiddleware",
  "users.middleware.RequestLoggingMiddleware",
]

ROOT_URLCONF = "Ecomerce_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Ecomerce_app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": verify_env("DB_NAME"),
#         "USER": verify_env("DB_USER"),
#         "PASSWORD": verify_env("DB_PASSWORD"),
#         "HOST": verify_env("DB_HOST"),
#         "PORT": verify_env("DB_PORT")
#     }
# }

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get("DABASE_URL"),
        conn_max_age=600,
        ssl_require=False
    )
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
#Custom user model
AUTH_USER_MODEL = "users.Users"

#Custome Authentication
AUTHENTICATION_BACKEND = [
  'users.backends.EmailBackend',
  'django.contrib.auth.backends.Modelbackend'
]

#Loging Request Condfiguration

LOGGING_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGGING_DIR, exist_ok=True)
LOGGING = {
  "version": 1,
  "disable_existing_loggers": False,
  "formatters" :{
    "verbose": {
      "format": "[%(asctime)s] %(levelname)s %(name)s %(message)s",
    },
  },
  "handlers":{
    "file":{
      "level": "INFO",
      "class": "logging.FileHandler",
      "filename": os.path.join(LOGGING_DIR, 'requests.log'),
      "formatter": "verbose",
    },
  },
  "loggers":{
    "request_loggers":{
      "handlers": ["file"],
      "level": "INFO",
      "propagate": False,
    },
  },
}

#Exception Handler
REST_FRAMEWORK = {
  #'EXCEPTION_HANDLER': 'Ecomerce_app.exceptions.custom_exception_handler',
  'DEFAULT_AUTHENTICATION_CLASSES': (
    'rest_framework_simplejwt.authentication.JWTAuthentication',
  ),
  "DEFAULT_PERMISSION_CLASSES": [
    "rest_framework.permissions.IsAuthenticated",
  ],
}


from datetime import timedelta

SIMPLE_JWT = {
  'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # how long access tokens are valid
  'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # how long refresh tokens are valid
  'ROTATE_REFRESH_TOKENS': True,                  # issue new refresh token on use
  'BLACKLIST_AFTER_ROTATION': True,              # old refresh tokens get blacklisted
  'AUTH_HEADER_TYPES': ('Bearer',),              # expects 'Authorization: Bearer <token>'
}

#swagger settings

SWAGGER_SETTINGS = {
  'SECURITY_DEFINITIONS': {
    'Bearer': {
      'type': 'apiKey',
      'name': 'Authorization',
      'in': 'header',
      'description': "JWT Authorization header using the Bearer scheme. Example: 'Bearer <token>'",
    }
  }
}

#Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'markworship001@gmail.com'       # Replace with your Gmail
EMAIL_HOST_PASSWORD = 'ytcajgaleqopaihb'      # Use Gmail App Password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER