# Generated by Django 5.2.8 on 2025-11-21 19:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=367)),
                ("sku", models.CharField(max_length=267)),
                ("category", models.CharField(max_length=247)),
                ("manufactured_date", models.DateField()),
                ("expiry_date", models.DateField()),
                (
                    "product_image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("stock", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("OUT_OF_STOCK", "Out of Stock"),
                            ("DISCONTINUED", "Discontinued"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="ACTIVE",
                        max_length=50,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
