# Generated by Django 5.2.8 on 2025-11-22 06:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_listing", "0002_alter_productmodel_product_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favourite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_added"],
            },
        ),
        migrations.AddIndex(
            model_name="productmodel",
            index=models.Index(
                fields=["category", "status"], name="product_lis_categor_0289b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productmodel",
            index=models.Index(
                fields=["price", "date_added"], name="product_lis_price_284812_idx"
            ),
        ),
        migrations.AddField(
            model_name="favourite",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favourited_by",
                to="product_listing.productmodel",
            ),
        ),
        migrations.AddField(
            model_name="favourite",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favourite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favourite",
            unique_together={("user_id", "product_id")},
        ),
    ]
