# Generated by Django 5.2.8 on 2025-11-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_listing", "0004_ratings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="image_photos/"),
        ),
    ]
