# Generated by Django 5.2.8 on 2025-11-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_listing", "0006_alter_productmodel_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="product_image",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="image_photos/"
            ),
        ),
    ]
