# Generated by Django 5.2.8 on 2025-11-24 11:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_listing", "0007_alter_productmodel_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="product_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image_photos"
            ),
        ),
    ]
