# Generated by Django 5.2.8 on 2025-11-26 23:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_listing", "0008_alter_productmodel_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="product_image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image_photos"
            ),
        ),
    ]
